# https://goreleaser.com
version: 2
project_name: tqm

before:
  hooks:
    - go mod tidy

# Build
builds:
  - id: tqm
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X "github.com/autobrr/tqm/pkg/runtime.Version={{ .Version }}"
      - -X "github.com/autobrr/tqm/pkg/runtime.GitCommit={{ .ShortCommit }}"
      - -X "github.com/autobrr/tqm/pkg/runtime.Timestamp={{ .Timestamp }}"
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    main: cmd/tqm/main.go
    binary: tqm

archives:
  - id: tqm
    ids:
      - tqm
    format_overrides:
      - goos: windows
        formats: ['zip']

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

snapshot:
  version_template: "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-dev+{{ .ShortCommit }}"

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/autobrr/tqm/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ## What to do next?
    
    - Read the [documentation](https://autobrr.com)
    - Join our [Discord server](https://discord.autobrr.com)

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
